# Generated by Django 5.1.4 on 2025-01-14 10:57

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        choices=[
                            ("#00FF00", "green"),
                            ("#FF0000", "red"),
                            ("#0000FF", "blue"),
                        ],
                        default="#FFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        choices=[
                            ("#0000FF", "blue"),
                            ("#00FF00", "green"),
                            ("#FF0000", "red"),
                        ],
                        default="#FFFFFF",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionStatePath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action",
                        to="statemanager.action",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="ending_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ending_state",
                to="statemanager.state",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="starting_state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starting_state",
                to="statemanager.state",
            ),
        ),
    ]
