# Generated by Django 5.1.4 on 2024-12-23 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("statemanager", "0002_actionstatepath"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionstatepath",
            name="state",
        ),
        migrations.RemoveField(
            model_name="actionstatepath",
            name="user",
        ),
    ]
